import { DiaryEntry, DailyHighlight, DailyReflection, Task, User, SpecialMoment } from '../types';
import { getTodayDateString } from './constants';

export const INITIAL_USER: User = {
  id: 'user-shamyuktha',
  name: 'Shamyuktha',
  email: 'shamyuktham6006@gmail.com',
  bio: 'Computer Science student & aspiring software engineer.',
  role: 'Student & Developer',
  createdAt: '2026-09-01T08:00:00Z',
  preferences: {
    theme: 'light',
    defaultPriority: 'medium',
    enableSounds: true,
    autoSaveIntervalMs: 2000,
  },
};

// Generate relative date string offset from today
function getDateOffset(daysOffset: number): string {
  const d = new Date();
  d.setDate(d.getDate() + daysOffset);
  const year = d.getFullYear();
  const month = String(d.getMonth() + 1).padStart(2, '0');
  const day = String(d.getDate()).padStart(2, '0');
  return `${year}-${month}-${day}`;
}

const today = getTodayDateString();
const yesterday = getDateOffset(-1);
const twoDaysAgo = getDateOffset(-2);
const threeDaysAgo = getDateOffset(-3);
const fourDaysAgo = getDateOffset(-4);
const fiveDaysAgo = getDateOffset(-5);
const sixDaysAgo = getDateOffset(-6);

export const INITIAL_TASKS: Task[] = [
  // Today's tasks
  {
    id: 'task-1',
    userId: 'user-shamyuktha',
    title: 'Complete Java assignment on Multi-threading',
    description: 'Implement producer-consumer problem using BlockingQueue and write unit tests.',
    priority: 'high',
    category: 'College',
    status: 'completed',
    dueDate: today,
    dueTime: '14:00',
    notes: 'Submitted to course portal on time.',
    createdAt: `${today}T08:30:00Z`,
    updatedAt: `${today}T13:45:00Z`,
    completedAt: `${today}T13:45:00Z`,
  },
  {
    id: 'task-2',
    userId: 'user-shamyuktha',
    title: 'Attend DBMS lecture & database normalization lab',
    description: 'Review BCNF and 4NF forms with professor notes.',
    priority: 'medium',
    category: 'College',
    status: 'completed',
    dueDate: today,
    dueTime: '11:30',
    notes: 'Took detailed notes on Boyce-Codd normal form.',
    createdAt: `${today}T08:30:00Z`,
    updatedAt: `${today}T11:40:00Z`,
    completedAt: `${today}T11:40:00Z`,
  },
  {
    id: 'task-3',
    userId: 'user-shamyuktha',
    title: 'Work on DayFlow personal portfolio project',
    description: 'Refine responsive layouts and connect diary autosave feature.',
    priority: 'high',
    category: 'Project',
    status: 'completed',
    dueDate: today,
    dueTime: '18:00',
    notes: 'Created clean distraction-free writing experience.',
    createdAt: `${today}T09:00:00Z`,
    updatedAt: `${today}T17:15:00Z`,
    completedAt: `${today}T17:15:00Z`,
  },
  {
    id: 'task-4',
    userId: 'user-shamyuktha',
    title: 'Read Spring Boot 3.4 microservices documentation',
    description: 'Understand Spring Cloud Gateway and JWT auth integration patterns.',
    priority: 'medium',
    category: 'Learning',
    status: 'completed',
    dueDate: today,
    dueTime: '19:30',
    notes: 'Saved key code snippets for reference.',
    createdAt: `${today}T09:15:00Z`,
    updatedAt: `${today}T19:10:00Z`,
    completedAt: `${today}T19:10:00Z`,
  },
  {
    id: 'task-5',
    userId: 'user-shamyuktha',
    title: 'Evening workout & 30-minute cardio session',
    description: 'Stretching and 5km steady run at campus track.',
    priority: 'medium',
    category: 'Health',
    status: 'completed',
    dueDate: today,
    dueTime: '20:15',
    createdAt: `${today}T09:20:00Z`,
    updatedAt: `${today}T20:45:00Z`,
    completedAt: `${today}T20:45:00Z`,
  },
  {
    id: 'task-6',
    userId: 'user-shamyuktha',
    title: 'Prepare presentation slides for Distributed Systems project',
    description: 'Design 8 architecture slides explaining consensus algorithm choices.',
    priority: 'high',
    category: 'College',
    status: 'in_progress',
    dueDate: today,
    dueTime: '22:00',
    notes: 'Drafted 5 of 8 slides, finishing diagrams tonight.',
    createdAt: `${today}T10:00:00Z`,
    updatedAt: `${today}T20:30:00Z`,
  },
  {
    id: 'task-7',
    userId: 'user-shamyuktha',
    title: 'Review peer pull requests on GitHub repository',
    description: 'Provide feedback on auth middleware and input validation tests.',
    priority: 'low',
    category: 'Project',
    status: 'pending',
    dueDate: today,
    dueTime: '23:00',
    createdAt: `${today}T10:15:00Z`,
    updatedAt: `${today}T10:15:00Z`,
  },
  {
    id: 'task-8',
    userId: 'user-shamyuktha',
    title: 'Call family and catch up with parents',
    description: 'Share weekend updates and upcoming exam schedule.',
    priority: 'low',
    category: 'Personal',
    status: 'pending',
    dueDate: today,
    dueTime: '21:30',
    createdAt: `${today}T10:30:00Z`,
    updatedAt: `${today}T10:30:00Z`,
  },

  // Yesterday's tasks
  {
    id: 'task-y1',
    userId: 'user-shamyuktha',
    title: 'Attend Operating Systems seminar',
    priority: 'high',
    category: 'College',
    status: 'completed',
    dueDate: yesterday,
    createdAt: `${yesterday}T08:00:00Z`,
    updatedAt: `${yesterday}T12:00:00Z`,
    completedAt: `${yesterday}T12:00:00Z`,
  },
  {
    id: 'task-y2',
    userId: 'user-shamyuktha',
    title: 'Solve 3 LeetCode dynamic programming questions',
    priority: 'medium',
    category: 'Learning',
    status: 'completed',
    dueDate: yesterday,
    createdAt: `${yesterday}T09:00:00Z`,
    updatedAt: `${yesterday}T16:00:00Z`,
    completedAt: `${yesterday}T16:00:00Z`,
  },
  {
    id: 'task-y3',
    userId: 'user-shamyuktha',
    title: 'Weekly grocery shopping & meal prep',
    priority: 'low',
    category: 'Personal',
    status: 'completed',
    dueDate: yesterday,
    createdAt: `${yesterday}T10:00:00Z`,
    updatedAt: `${yesterday}T18:00:00Z`,
    completedAt: `${yesterday}T18:00:00Z`,
  },
  {
    id: 'task-y4',
    userId: 'user-shamyuktha',
    title: 'Hydration goal: 2.5 Liters of water',
    priority: 'low',
    category: 'Health',
    status: 'completed',
    dueDate: yesterday,
    createdAt: `${yesterday}T08:00:00Z`,
    updatedAt: `${yesterday}T21:00:00Z`,
    completedAt: `${yesterday}T21:00:00Z`,
  },

  // 2 days ago
  {
    id: 'task-2d1',
    userId: 'user-shamyuktha',
    title: 'Set up PostgreSQL Docker container for local dev',
    priority: 'medium',
    category: 'Project',
    status: 'completed',
    dueDate: twoDaysAgo,
    createdAt: `${twoDaysAgo}T09:00:00Z`,
    updatedAt: `${twoDaysAgo}T14:00:00Z`,
    completedAt: `${twoDaysAgo}T14:00:00Z`,
  },
  {
    id: 'task-2d2',
    userId: 'user-shamyuktha',
    title: 'Draft resume for upcoming campus tech placement drives',
    priority: 'high',
    category: 'Learning',
    status: 'completed',
    dueDate: twoDaysAgo,
    createdAt: `${twoDaysAgo}T10:00:00Z`,
    updatedAt: `${twoDaysAgo}T17:30:00Z`,
    completedAt: `${twoDaysAgo}T17:30:00Z`,
  },

  // 3 days ago
  {
    id: 'task-3d1',
    userId: 'user-shamyuktha',
    title: 'Study Computer Networks: TCP/IP handshake and congestion control',
    priority: 'high',
    category: 'College',
    status: 'completed',
    dueDate: threeDaysAgo,
    createdAt: `${threeDaysAgo}T08:00:00Z`,
    updatedAt: `${threeDaysAgo}T15:00:00Z`,
    completedAt: `${threeDaysAgo}T15:00:00Z`,
  },
  {
    id: 'task-3d2',
    userId: 'user-shamyuktha',
    title: 'Gym core workout & mobility drills',
    priority: 'medium',
    category: 'Health',
    status: 'completed',
    dueDate: threeDaysAgo,
    createdAt: `${threeDaysAgo}T09:00:00Z`,
    updatedAt: `${threeDaysAgo}T19:00:00Z`,
    completedAt: `${threeDaysAgo}T19:00:00Z`,
  },

  // 4 days ago
  {
    id: 'task-4d1',
    userId: 'user-shamyuktha',
    title: 'Complete Software Engineering requirements specification diagram',
    priority: 'medium',
    category: 'College',
    status: 'completed',
    dueDate: fourDaysAgo,
    createdAt: `${fourDaysAgo}T10:00:00Z`,
    updatedAt: `${fourDaysAgo}T16:00:00Z`,
    completedAt: `${fourDaysAgo}T16:00:00Z`,
  },

  // 5 days ago
  {
    id: 'task-5d1',
    userId: 'user-shamyuktha',
    title: 'Research vector databases and semantic indexing techniques',
    priority: 'medium',
    category: 'Learning',
    status: 'completed',
    dueDate: fiveDaysAgo,
    createdAt: `${fiveDaysAgo}T09:00:00Z`,
    updatedAt: `${fiveDaysAgo}T14:30:00Z`,
    completedAt: `${fiveDaysAgo}T14:30:00Z`,
  },

  // 6 days ago
  {
    id: 'task-6d1',
    userId: 'user-shamyuktha',
    title: 'Build clean design tokens in Tailwind CSS',
    priority: 'high',
    category: 'Project',
    status: 'completed',
    dueDate: sixDaysAgo,
    createdAt: `${sixDaysAgo}T09:00:00Z`,
    updatedAt: `${sixDaysAgo}T16:45:00Z`,
    completedAt: `${sixDaysAgo}T16:45:00Z`,
  },
];

export const INITIAL_DIARY_ENTRIES: DiaryEntry[] = [
  {
    id: 'diary-today',
    userId: 'user-shamyuktha',
    date: today,
    title: 'A Productive Rhythm & Clear Progress',
    content: `<p>Today felt grounded and genuinely fulfilling. I woke up around 7:00 AM with clear intent for what I wanted to accomplish. Finishing the Java multi-threading assignment before lunch gave me a tremendous wave of momentum.</p><p>During the DBMS lab, our professor walked through practical query optimization techniques which clicked immediately. In the afternoon, I dove deep into the DayFlow interface architecture, creating seamless transitions between task completions and mindful journaling.</p><blockquote>"Small consistent actions compound into genuine confidence."</blockquote><p>The evening workout helped clear my mind after hours in front of code. Looking ahead to tomorrow, I want to finalize the presentation slides and continue maintaining this balanced cadence.</p>`,
    mood: 'happy',
    tags: ['#college', '#project', '#learning', '#achievement'],
    linkedTaskIds: ['task-1', 'task-2', 'task-3', 'task-5'],
    wordCount: 135,
    createdAt: `${today}T18:40:00Z`,
    updatedAt: `${today}T20:55:00Z`,
  },
  {
    id: 'diary-yesterday',
    userId: 'user-shamyuktha',
    date: yesterday,
    title: 'Quiet Focus and Problem Solving',
    content: `<p>Sunday was quiet and introspective. I spent quality time practicing dynamic programming problems. The first one on memoized grid traversal was tricky, but breaking it down onto physical paper first helped me see the sub-problem overlaps clearly.</p><p>Took time to organize my study desk and plan the upcoming week's milestones. Having everything prepared beforehand dramatically lowers cognitive friction on Monday mornings.</p>`,
    mood: 'calm',
    tags: ['#learning', '#focus', '#routine'],
    linkedTaskIds: ['task-y2', 'task-y3'],
    wordCount: 78,
    createdAt: `${yesterday}T20:15:00Z`,
    updatedAt: `${yesterday}T21:10:00Z`,
  },
  {
    id: 'diary-2d',
    userId: 'user-shamyuktha',
    date: twoDaysAgo,
    title: 'Building Foundations and Career Planning',
    content: `<p>Spent the morning revising my technical resume and updating project descriptions to highlight concrete metrics and system architecture choices. Setting up PostgreSQL inside Docker took a few extra minutes because of a port conflict, but resolving it reminded me how much I enjoy debugging dev environments.</p>`,
    mood: 'motivated',
    tags: ['#project', '#career'],
    linkedTaskIds: ['task-2d1', 'task-2d2'],
    wordCount: 54,
    createdAt: `${twoDaysAgo}T19:30:00Z`,
    updatedAt: `${twoDaysAgo}T20:00:00Z`,
  },
  {
    id: 'diary-3d',
    userId: 'user-shamyuktha',
    date: threeDaysAgo,
    title: 'Deep Dive into Network Protocols',
    content: `<p>Our lecture on TCP/IP protocol stack was eye-opening. Understanding sliding window flow control and congestion avoidance in real network packets puts web development abstractions into a whole new perspective.</p>`,
    mood: 'excited',
    tags: ['#college', '#learning'],
    linkedTaskIds: ['task-3d1'],
    wordCount: 38,
    createdAt: `${threeDaysAgo}T21:00:00Z`,
    updatedAt: `${threeDaysAgo}T21:20:00Z`,
  },
  {
    id: 'diary-4d',
    userId: 'user-shamyuktha',
    date: fourDaysAgo,
    title: 'Design Diagrams & System Modeling',
    content: `<p>Spent substantial time mapping use-case diagrams and sequence flows for our semester software engineering project. Visualizing data boundaries before writing code saves so much refactoring later.</p>`,
    mood: 'calm',
    tags: ['#college', '#project'],
    linkedTaskIds: ['task-4d1'],
    wordCount: 36,
    createdAt: `${fourDaysAgo}T20:30:00Z`,
    updatedAt: `${fourDaysAgo}T20:30:00Z`,
  },
  {
    id: 'diary-5d',
    userId: 'user-shamyuktha',
    date: fiveDaysAgo,
    title: 'Curiosity Sparks in Modern AI Retrieval',
    content: `<p>Explored vector indexing mechanisms (HNSW and IVF) and how high-dimensional cosine similarity powers semantic retrieval. The math behind approximate nearest neighbor search is elegant.</p>`,
    mood: 'excited',
    tags: ['#learning'],
    linkedTaskIds: ['task-5d1'],
    wordCount: 32,
    createdAt: `${fiveDaysAgo}T20:45:00Z`,
    updatedAt: `${fiveDaysAgo}T21:00:00Z`,
  },
  {
    id: 'diary-6d',
    userId: 'user-shamyuktha',
    date: sixDaysAgo,
    title: 'Design System Craft and Attention to Detail',
    content: `<p>Worked on building clean spacing math, nested border-radius proportions, and accessible color tokens. When typography and negative space are treated with care, software feels effortless to use.</p>`,
    mood: 'motivated',
    tags: ['#project'],
    linkedTaskIds: ['task-6d1'],
    wordCount: 34,
    createdAt: `${sixDaysAgo}T19:50:00Z`,
    updatedAt: `${sixDaysAgo}T20:10:00Z`,
  },
];

export const INITIAL_REFLECTIONS: DailyReflection[] = [
  {
    id: 'ref-today',
    userId: 'user-shamyuktha',
    date: today,
    wentWell: 'Finished the Java assignment ahead of the deadline and stayed energized throughout classes.',
    challenges: 'Balancing evening coding time with slide preparation required conscious focus and eliminating distractions.',
    learned: 'Concurrency primitives become much easier when thinking in terms of shared state invariants first.',
    gratitude: 'Grateful for supportive classmates who shared test cases, and a peaceful evening workout.',
    improveTomorrow: 'Start the distributed systems presentation in the morning rather than deferring it to late evening.',
    updatedAt: `${today}T20:58:00Z`,
  },
  {
    id: 'ref-yesterday',
    userId: 'user-shamyuktha',
    date: yesterday,
    wentWell: 'Maintained calm focus while practicing algorithms without checking social media.',
    challenges: 'Felt slight mental fatigue after 2 hours of continuous recursion tracing.',
    learned: 'Drawing recursion trees on paper clarifies memoization sub-problems faster than mental simulation.',
    gratitude: 'Grateful for a quiet Sunday and healthy home-cooked meals.',
    improveTomorrow: 'Take a short 5-minute stretch break every 45 minutes.',
    updatedAt: `${yesterday}T21:12:00Z`,
  },
];

export const INITIAL_HIGHLIGHTS: DailyHighlight[] = [
  {
    id: 'hl-today-1',
    userId: 'user-shamyuktha',
    date: today,
    text: 'Completed and submitted Java multi-threading assignment on time ⭐',
    createdAt: `${today}T13:46:00Z`,
  },
  {
    id: 'hl-today-2',
    userId: 'user-shamyuktha',
    date: today,
    text: 'Built the seamless Task ↔ Diary connection in DayFlow',
    createdAt: `${today}T17:16:00Z`,
  },
  {
    id: 'hl-today-3',
    userId: 'user-shamyuktha',
    date: today,
    text: 'Completed 5km campus run under evening breeze',
    createdAt: `${today}T20:46:00Z`,
  },
  {
    id: 'hl-y-1',
    userId: 'user-shamyuktha',
    date: yesterday,
    text: 'Solved a tough LeetCode hard problem using DP memoization',
    createdAt: `${yesterday}T16:05:00Z`,
  },
  {
    id: 'hl-2d-1',
    userId: 'user-shamyuktha',
    date: twoDaysAgo,
    text: 'Polished technical resume and received positive peer feedback',
    createdAt: `${twoDaysAgo}T17:35:00Z`,
  },
];

export const INITIAL_SPECIAL_MOMENTS: SpecialMoment[] = [
  {
    id: 'moment-today-1',
    userId: 'user-shamyuktha',
    date: today,
    title: 'Semester Tech Fest & Hackathon Champions! 🏆',
    type: 'achievement',
    note: 'Our 4-person team built an automated campus emergency response portal and won 1st place! Hard work over 36 hours paid off. Proud of what we built.',
    photoUrl: 'https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&w=1200&q=80',
    photoCaption: 'With the team holding our trophy and project showcase banner',
    location: 'Main Auditorium, Tech Block',
    tags: ['hackathon', 'first-place', 'proud', 'teamwork'],
    emoji: '🏆',
    isSpecialDay: true,
    createdAt: `${today}T15:30:00Z`,
    updatedAt: `${today}T15:30:00Z`,
  },
  {
    id: 'moment-yesterday-1',
    userId: 'user-shamyuktha',
    date: yesterday,
    title: 'Sunrise Campus Walk & Golden Hour Coffee ☕',
    type: 'personal',
    note: 'Woke up early at 6:00 AM. Walked through the campus botanical garden under golden autumn light, then grabbed warm South Indian filter coffee with Divya. Feeling grounded and calm.',
    photoUrl: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=1200&q=80',
    photoCaption: 'Early morning coffee steam against the golden autumn sunshine',
    location: 'Campus Botanical Garden & Cafe',
    tags: ['coffee', 'peaceful', 'friendship', 'morning-routine'],
    emoji: '☕',
    isSpecialDay: false,
    createdAt: `${yesterday}T07:45:00Z`,
    updatedAt: `${yesterday}T07:45:00Z`,
  },
  {
    id: 'moment-24th-1',
    userId: 'user-shamyuktha',
    date: fourDaysAgo,
    title: "Sneha's 21st Birthday Surprise! 🎂",
    type: 'birthday',
    note: 'Organized a surprise celebration with handwritten letters, mango cheesecake, and polaroid photos. Seeing her genuine surprise and happy tears made this day truly special.',
    photoUrl: 'https://images.unsplash.com/photo-1513151233558-d860c5398176?auto=format&fit=crop&w=1200&q=80',
    photoCaption: 'Surprise celebration, confetti and warm fairy lights',
    location: 'The Rusty Lantern Bistro',
    tags: ['birthday', 'best-friends', 'memories', 'celebration'],
    emoji: '🎂',
    isSpecialDay: true,
    createdAt: `${fourDaysAgo}T19:00:00Z`,
    updatedAt: `${fourDaysAgo}T19:00:00Z`,
  },
  {
    id: 'moment-trip-1',
    userId: 'user-shamyuktha',
    date: getDateOffset(-12),
    title: 'Weekend Trek to Mountain Viewpoint ⛰️',
    type: 'trip',
    note: 'Escaped the city hustle for a day. Reached the highest peak right as the mist cleared to reveal the blue lake below. Deep breaths and fresh pine air.',
    photoUrl: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80',
    photoCaption: 'Panoramic view from the summit looking over the valley',
    location: 'Emerald Peak Trail',
    tags: ['hiking', 'nature', 'refresh', 'travel'],
    emoji: '✈️',
    isSpecialDay: true,
    createdAt: `${getDateOffset(-12)}T11:20:00Z`,
    updatedAt: `${getDateOffset(-12)}T11:20:00Z`,
  },
  {
    id: 'moment-milestone-1',
    userId: 'user-shamyuktha',
    date: getDateOffset(-18),
    title: 'Semester Project Architecture Approved 🎓',
    type: 'milestone',
    note: 'Presented our high-concurrency microservices design to the departmental review board. Received high praise and green light for final deployment!',
    photoUrl: 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=1200&q=80',
    photoCaption: 'After our defense review in the departmental conference hall',
    location: 'CSE Department Seminar Hall',
    tags: ['college', 'milestone', 'academics', 'success'],
    emoji: '🎓',
    isSpecialDay: true,
    createdAt: `${getDateOffset(-18)}T16:00:00Z`,
    updatedAt: `${getDateOffset(-18)}T16:00:00Z`,
  },
];

